# dev环境
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: carl1223
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    mapper-locations: classpath:/mappers/*.xml